---
- name: Playbook for backup grafana roles
  hosts: all
  vars_files:
    - vars.yaml
  tasks:
    - name: Create a backup directory on the host
      ansible.builtin.file:
        path: '{{ backup_dir }}'
        state: directory
        mode: '0755'

    - name: Run Docker container for backup
      ansible.builtin.command: "docker run --rm --name backup-container -e GRAFANA_URL={{ grafana_url }} -e API_KEY={{ grafana_token }} -v {{ backup_dir }}:/app/grafana_backup {{ backup_image }}"
      register: backup_status

    - debug:
        var: backup_status.stdout_lines
