---
- name: Playbook for backup grafana roles
  hosts: all
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - name: Ensure Python and Virtualenv are installed with apt
      ansible.builtin.apt:
        name:
          - python3
          - python3-venv
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Create virtual environment
      ansible.builtin.command: python3 -m venv "{{ venv_dir }}"
      args:
        creates: "{{ venv_dir }}"
      register: venv_creation

    - name: Copy backup script to target
      ansible.builtin.template:
        src: "backup.py.j2"
        dest: "{{ venv_dir }}/bin/backup.py"
        mode: '0755'

    - name: Install dependencies in virtual environment
      ansible.builtin.command: "{{ venv_dir }}/bin/pip3 install requests regex"

    - name: Run backup script
      ansible.builtin.command: "{{ venv_dir }}/bin/python {{ venv_dir }}/bin/backup.py"
      register: backup_status

    - debug:
        var: backup_status.stdout_lines
